resources:
- ../base
- ./../../../../../../apps/dummy-app/1.0

namespace: stockholm-busybox-line

configMapGenerator:
- name: configuration-ipaddresses
  behavior: replace
  files:
  - ipaddresses.config.json
  
images:
- name: scr.io/library/busybox
  newName: busybox
