resources:
- ../base
- ./../../../../../../apps/moonshot-sample/1.0

namespace: moonshot-sample

configMapGenerator:
- name: input-configuration
  behavior: merge
  files:
  - tags=tags-configuration.yaml
